file(GLOB_RECURSE public_headers "${SOURCE_ROOT}/src/AnimationRuntime/*.h" "${SOURCE_ROOT}/src/AnimationRuntime/*.hpp")
list(FILTER public_headers EXCLUDE REGEX "/(Adapters|Granny)/")
if(NOT public_headers)
    message(FATAL_ERROR "Animation Runtime public headers are missing")
endif()
foreach(header IN LISTS public_headers)
    file(READ "${header}" contents)
    string(TOLOWER "${contents}" lower_contents)
    if(lower_contents MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*(granny|gltf|assimp|windows|d3d|dxgi|diligent|ozz)")
        message(FATAL_ERROR "Platform/provider include leaked into ${header}")
    endif()
    if(contents MATCHES "(^|[^A-Za-z0-9_])(granny_[A-Za-z0-9_]+|cgltf_[A-Za-z0-9_]+|ai(Scene|Node|Mesh|Animation|Quaternion|Matrix[A-Za-z0-9_]*)|HWND|HINSTANCE|HMODULE|HANDLE|DWORD|WPARAM|LPARAM|HRESULT|LRESULT|BOOL|BYTE|RECT|POINT|ID3D[A-Za-z0-9_]*|IDXGI[A-Za-z0-9_]*)([^A-Za-z0-9_]|$)" OR contents MATCHES "(Diligent|fastgltf|Assimp|ozz)::")
        message(FATAL_ERROR "Platform/provider type leaked into ${header}")
    endif()
endforeach()
list(LENGTH public_headers count)
message(STATUS "PASS: ${count} Animation Runtime public headers contain only neutral interfaces")
