# ZiiNAN: Legacy D3D9 renderer removed from production path.
# Source architecture guard, not a replacement for runtime resource/draw telemetry.
foreach(legacy src/EterLib/LegacyD3D9Backend.cpp src/EterLib/LegacyD3D9Backend.h)
    if(EXISTS "${SOURCE_ROOT}/${legacy}")
        message(FATAL_ERROR "Functional Legacy backend reintroduced: ${legacy}")
    endif()
endforeach()
file(GLOB_RECURSE production "${SOURCE_ROOT}/src/*.cpp" "${SOURCE_ROOT}/src/*.h")
foreach(path IN LISTS production)
    file(READ "${path}" source)
    # The production factory and device-dispatch methods must not come back.
    if(source MATCHES "Direct3DCreate9|CreateDeviceEx|D3DTS_|D3DTRANSFORMSTATETYPE")
        message(FATAL_ERROR "Native D3D9 device/transform entry point: ${path}")
    endif()
    if(source MATCHES "ms_lpd3dDevice[ \t]*->[ \t]*(BeginScene|EndScene|Clear|Present|PresentEx|Reset|ResetEx|DrawPrimitive|DrawPrimitiveUP|DrawIndexedPrimitive|DrawIndexedPrimitiveUP|SetTransform|SetTextureStageState|SetRenderState|SetSamplerState)[ \t]*\\(")
        message(FATAL_ERROR "Native device frame/draw/state dispatch: ${path}")
    endif()
endforeach()
foreach(path src/EterLib/StateManager.h src/EterLib/StateManager.cpp src/EterLib/NativeStateView.h)
    file(READ "${SOURCE_ROOT}/${path}" source)
    if(source MATCHES "m_lpD3DDev|GetDevice\\(")
        message(FATAL_ERROR "CPU draw descriptions must not consult a device: ${path}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/src/Renderer/ResourceData.h" resources)
if(NOT resources MATCHES "constexpr bool UseNeutralResources\\(\\) *\\{ *return true;")
    message(FATAL_ERROR "Production resource routing must be immutable and neutral")
endif()
message(STATUS "No Legacy factory/backend, native frame/draw dispatch, device state cache or D3D9 matrix slots")
