# ZiiNAN: Removed final D3D9 compile-time dependency.
# Reject API/header/library dependencies, not historical explanatory comments.
file(GLOB_RECURSE production "${SOURCE_ROOT}/src/*.cpp" "${SOURCE_ROOT}/src/*.h")
foreach(path IN LISTS production)
    file(READ "${path}" source)
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" source "${source}")
    string(REGEX REPLACE "//[^\n]*" "" source "${source}")
    if(source MATCHES "(d3d9[a-zA-Z0-9_]*|d3dx9[a-zA-Z0-9_]*)[.]h|IDirect3D|LPDIRECT3D|D3DX[A-Za-z0-9_]*|Direct3DCreate9|CreateDeviceEx|D3D(RS_|TSS_|SAMP_|TS_|FMT_|POOL_|USAGE_|FVF_|PT_)|D3D(FORMAT|POOL|USAGE|PRIMITIVETYPE|CULL|BLEND|CMPFUNC|TEXTUREADDRESS|TEXTUREFILTERTYPE|TRANSFORMSTATETYPE|RENDERSTATETYPE|MATERIAL9|LIGHT9|COLORVALUE|VIEWPORT9|CAPS9|PRESENT_PARAMETERS)|M2_ENABLE_DILIGENT_D3D11")
        message(FATAL_ERROR "Obsolete production graphics dependency: ${path}")
    endif()
endforeach()
foreach(path src/EterLib/DrawState.h src/EterLib/DrawState.cpp src/EterLib/DrawStateView.h)
    file(READ "${SOURCE_ROOT}/${path}" source)
    if(source MATCHES "GetDevice\\(|DrawPrimitive|DrawIndexedPrimitive|GetD3D")
        message(FATAL_ERROR "CPU draw data must not execute graphics APIs: ${path}")
    endif()
endforeach()
file(GLOB_RECURSE build_scripts "${SOURCE_ROOT}/src/CMakeLists.txt" "${SOURCE_ROOT}/src/*.cmake" "${SOURCE_ROOT}/extern/CMakeLists.txt" "${SOURCE_ROOT}/extern/*.cmake")
list(APPEND build_scripts "${SOURCE_ROOT}/CMakeLists.txt")
foreach(path IN LISTS build_scripts)
    file(READ "${path}" script)
    if(script MATCHES "[dD]3[dD][xX]?9[^\n\r]*[.](lib|h)|M2_ENABLE_DILIGENT_D3D11")
        message(FATAL_ERROR "Obsolete build dependency: ${path}")
    endif()
endforeach()
message(STATUS "Production API/header/types and build dependency audit: PASS")
