function(m2_collect_targets directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        m2_collect_targets("${child}" child_targets)
        list(APPEND targets ${child_targets})
    endforeach()
    set(${output} "${targets}" PARENT_SCOPE)
endfunction()

function(m2_audit_platform_targets)
    m2_collect_targets("${PROJECT_SOURCE_DIR}" targets)
    set(report "System=${CMAKE_SYSTEM_NAME}\nProcessor=${CMAKE_SYSTEM_PROCESSOR}\nPointerBytes=${CMAKE_SIZEOF_VOID_P}\nAndroidABI=${CMAKE_ANDROID_ARCH_ABI}\n")
    if(NOT M2_BUILD_WINDOWS_CLIENT)
        foreach(forbidden UserInterface M2Platform M2PlatformWindowsFeatures WindowsInput WebView Granny SpeedTree Python
            M2RendererDiligent Diligent-GraphicsEngineD3D11-static)
            if(TARGET ${forbidden})
                message(FATAL_ERROR "Windows/game target leaked into portable/Android build: ${forbidden}")
            endif()
        endforeach()
    endif()
    foreach(target IN LISTS targets)
        if(target MATCHES "^(M2|Platform)")
            get_target_property(sources ${target} SOURCES)
            get_target_property(links ${target} LINK_LIBRARIES)
            get_target_property(interface_links ${target} INTERFACE_LINK_LIBRARIES)
            if(NOT M2_BUILD_WINDOWS_CLIENT)
                if("${sources}" MATCHES "Windows/|DiligentD3D11|Win32")
                    message(FATAL_ERROR "Windows source in ${target}: ${sources}")
                endif()
                if("${links};${interface_links}" MATCHES "(^|;)(user32|gdi32|winmm|ws2_32|shell32|ole32|d3d11|dxgi|Dbghelp)(;|$)")
                    message(FATAL_ERROR "Windows library in ${target}: ${links};${interface_links}")
                endif()
            endif()
            string(APPEND report "\n${target}\n  sources=${sources}\n  links=${links}\n  interface=${interface_links}\n")
        endif()
    endforeach()
    file(WRITE "${CMAKE_BINARY_DIR}/platform-target-audit.txt" "${report}")
    message(STATUS "Platform target separation verified; see platform-target-audit.txt")
endfunction()
