# Configure-time copies preserve the pinned dependency checkout.
find_package(Python3 COMPONENTS Interpreter REQUIRED)
set(m2_shader_audit_dir "${CMAKE_CURRENT_BINARY_DIR}/shader-load-audit")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/buildtool/PrepareShaderLoadAudit.py"
    "${diligentcore_SOURCE_DIR}" "${m2_shader_audit_dir}" RESULT_VARIABLE m2_shader_audit_result)
if(NOT m2_shader_audit_result EQUAL 0)
    message(FATAL_ERROR "Could not prepare pinned shader load instrumentation")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/buildtool/PrepareShaderLoadAudit.py")
function(m2_shader_audit_source target filename)
    get_target_property(sources ${target} SOURCES)
    list(FILTER sources EXCLUDE REGEX "(^|/)${filename}$")
    set_property(TARGET ${target} PROPERTY SOURCES "${sources}")
    target_sources(${target} PRIVATE "${m2_shader_audit_dir}/${filename}")
    target_include_directories(${target} PRIVATE "${PROJECT_SOURCE_DIR}/src" "${diligentcore_SOURCE_DIR}")
    target_compile_features(${target} PRIVATE cxx_std_17)
endfunction()
m2_shader_audit_source(Diligent-GraphicsEngineD3DBase ShaderD3DBase.cpp)
m2_shader_audit_source(Diligent-GraphicsEngineD3D11-static RenderDeviceD3D11Impl.cpp)
m2_shader_audit_source(Diligent-GraphicsEngineD3D11-static ShaderD3D11Impl.cpp)
# ShaderLoadAudit.h uses XXH128State from GraphicsTools in the instrumented source.
target_link_libraries(Diligent-GraphicsEngineD3D11-static PRIVATE Diligent-GraphicsTools)
