file(GLOB_RECURSE own_sources "${SOURCE_ROOT}/src/*.cpp" "${SOURCE_ROOT}/src/*.h")
list(FILTER own_sources EXCLUDE REGEX "/AssetRuntime/GlTF/")
foreach(path IN LISTS own_sources)
    file(READ "${path}" source)
    if(source MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*(cgltf|fastgltf)")
        message(FATAL_ERROR "Loader dependency leaked outside private provider: ${path}")
    endif()
endforeach()
message(STATUS "PASS: zero cgltf/fastgltf includes outside private provider")
