file(GLOB_RECURSE public_headers "${SOURCE_ROOT}/src/AssetRuntime/*.h" "${SOURCE_ROOT}/src/AssetRuntime/*.hpp")
list(FILTER public_headers EXCLUDE REGEX "/Granny/")
if(NOT public_headers)
    message(FATAL_ERROR "Asset Runtime public headers are missing")
endif()
foreach(header IN LISTS public_headers)
    file(READ "${header}" contents)
    if(contents MATCHES "#[ \t]*include[ \t]*[<\"][^>\"]*(granny|[Ww]indows\\.h|[Dd]3[dD]|[Dd][Xx][Gg][Ii]|Diligent|AssetRuntime/Granny)")
        message(FATAL_ERROR "Platform/provider include leaked into ${header}")
    endif()
    if(contents MATCHES "(^|[^A-Za-z0-9_])(granny_[A-Za-z0-9_]+|HWND|HINSTANCE|HMODULE|HANDLE|DWORD|WPARAM|LPARAM|HRESULT|LRESULT|BOOL|BYTE|RECT|POINT|ID3D[A-Za-z0-9_]*|IDXGI[A-Za-z0-9_]*)([^A-Za-z0-9_]|$)" OR contents MATCHES "Diligent::")
        message(FATAL_ERROR "Platform/provider type leaked into ${header}")
    endif()
endforeach()
list(LENGTH public_headers count)
message(STATUS "PASS: ${count} Asset Runtime public headers have no provider/platform/render backend types or includes")
