file(READ "${CMAKE_CURRENT_LIST_DIR}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}")
if(NOT count EQUAL 12)
    message(FATAL_ERROR "Expected exactly 12 preserved Classic references")
endif()
foreach(index RANGE 0 11)
    string(JSON image GET "${manifest}" ${index} image)
    string(JSON expected GET "${manifest}" ${index} sha256)
    file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/${image}" reference)
    file(SHA256 "${CAPTURE_DIRECTORY}/${image}" actual)
    if(NOT reference STREQUAL expected OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Classic byte mismatch: ${image}; expected=${expected}; reference=${reference}; actual=${actual}")
    endif()
endforeach()
message(STATUS "PASS: Classic 12/12 byte-identical to the preserved pre-CLEAN-X references")
