add_library(M2GraphicsSettings STATIC GraphicsSettings.cpp GraphicsSettingsFile.cpp SceneLighting.cpp)
target_include_directories(M2GraphicsSettings PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/..)
target_compile_features(M2GraphicsSettings PUBLIC cxx_std_20)
target_link_libraries(M2GraphicsSettings PRIVATE M2FirstPartyArchitectureChecks)
