file(GLOB runtime_sources "${SOURCE_ROOT}/src/Vegetation/*.h" "${SOURCE_ROOT}/src/Vegetation/*.cpp")
foreach(path IN LISTS runtime_sources)
    file(READ "${path}" source)
    if(source MATCHES "CSpeedTree|SpeedTreeRT[.]h|speedtree_static|LegacySPT|Assimp|assimp/")
        message(FATAL_ERROR "Offline SDK/tool leaked into vegetation runtime: ${path}")
    endif()
    if(path MATCHES "[.]h$" AND source MATCHES "windows[.]h|HWND|ID3D11|Diligent|cgltf|rapidjson")
        message(FATAL_ERROR "Implementation detail leaked into public vegetation header: ${path}")
    endif()
endforeach()
file(READ "${SOURCE_ROOT}/src/Vegetation/CMakeLists.txt" build)
if(build MATCHES "SpeedTree|LegacySPT|AssetTool|assimp|meshoptimizer")
    message(FATAL_ERROR "Vegetation target links offline dependencies")
endif()
message(STATUS "PASS: portable vegetation public boundary and SDK-free runtime sources/target")
