# Every production source and nested target is checked; optional tooling and historical evidence are separate.
file(GLOB_RECURSE sources "${SOURCE_ROOT}/src/*.h" "${SOURCE_ROOT}/src/*.cpp" "${SOURCE_ROOT}/src/*.c" "${SOURCE_ROOT}/src/CMakeLists.txt" "${SOURCE_ROOT}/extern/library/CMakeLists.txt")
foreach(path IN LISTS sources)
    file(READ "${path}" source)
    if(source MATCHES "[Ss][Pp][Ee][Ee][Dd][Tt][Rr][Ee][Ee]|LegacySPT|TreeRenderBridge|DiligentTreeRenderer|Vegetation::Mode|NativeEnabled")
        message(FATAL_ERROR "Legacy dependency or second vegetation runtime in production: ${path}")
    endif()
endforeach()
foreach(artifact extern/include/SpeedTreeRT.h extern/library/SpeedTree/speedtree_static.lib extern/library/SpeedTree/speedtree_staticd.lib src/SpeedTreeLib/SpeedTreeWrapper.cpp src/Renderer/DiligentTreeRenderer.cpp)
    if(EXISTS "${SOURCE_ROOT}/${artifact}")
        message(FATAL_ERROR "Legacy SDK/runtime artifact in production search tree: ${artifact}")
    endif()
endforeach()
message(STATUS "PASS: production legacy includes/types/calls/targets and SDK artifacts zero")
